FROM node:lts

# Create app directory
WORKDIR /usr/src/app

# Install global dependencies
RUN npm install -g npm@latest && npm cache clean --force

# Copy package files first to leverage Docker cache
COPY --chown=node:node package*.json ./

# Clear npm cache and install dependencies
RUN npm cache clean --force && npm i

# Copy the rest of the application code
COPY --chown=node:node . .

# Set environment variables
ENV API_URL=https://api.news.vedina.ir
ENV PORT=3000
ENV APP_VERSION=1.0.0
ENV TZ = 'Asia/Tehran'

ENV DB_HOST=mysql
ENV DB_NAME=news_blog
ENV DB_USER=news_blog
ENV DB_PASSWORD=

ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
ENV REDIS_PASSWORD=

ENV JWT_SECRET=""


# Expose the port the app runs on
EXPOSE 3000

# Switch to non-root user
USER node

# Default command (can be overridden in docker-compose)
CMD ["npm", "run", "dev"]