apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: newsblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          env:
            - name: UPLOAD_LIMIT
              value: "64M"
            - name: PMA_HOST
              value: "mysql"
            - name: PMA_PORT
              value: "3306"
