apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: newsblog
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30801
  type: NodePort
